# Generated by Django 2.1 on 2020-07-24 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_auto_20200724_1239'),
        ('djangoapp', '0002_auto_20200724_1236'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
