# Generated by Django 2.1 on 2020-07-25 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0011_auto_20200725_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
