# Generated by Django 2.1 on 2020-07-25 09:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0020_auto_20200725_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 25, 9, 23, 7, 477418, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 25, 9, 23, 7, 477455, tzinfo=utc)),
        ),
    ]
