# Generated by Django 2.1 on 2020-07-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telephone_no',
            field=models.IntegerField(default=977),
        ),
    ]
