# Generated by Django 2.1 on 2020-07-29 10:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_auto_20200729_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
